---
name: nop-commerce
services:
  nop:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
        - "5000"    
    networks:
      - nop-net
  nopdb:
    image: mysql:8.0-debian
    environment:
      - MYSQL_ROOT_PASSWORD=gani
      - MYSQL_DATABASE=nop
      - MYSQL_USER=gani
      - MYSQL_PASSWORD=gani    
    networks:
      - nop-net
    volumes:
      - nop-vol:/var/lib/mysql:rw

volumes:
    nop-vol:

networks:
    nop-net:    